// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQGUVUq48F4pwoTYTmJkEJSzV6qPdDheA',
    appId: '1:465631514254:web:0f8d4a775b9916e14a83df',
    messagingSenderId: '465631514254',
    projectId: 'group-2acd1',
    authDomain: 'group-2acd1.firebaseapp.com',
    storageBucket: 'group-2acd1.appspot.com',
    measurementId: 'G-HKWHJP0FPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD65GT57qelajaNQmfpQ0qShlrtfGqYPCQ',
    appId: '1:465631514254:android:a0507086a1a7a45f4a83df',
    messagingSenderId: '465631514254',
    projectId: 'group-2acd1',
    storageBucket: 'group-2acd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARiH87L4ejrq7YSuIigNhqZ89Gzxw8dzc',
    appId: '1:465631514254:ios:b71f8307445291644a83df',
    messagingSenderId: '465631514254',
    projectId: 'group-2acd1',
    storageBucket: 'group-2acd1.appspot.com',
    iosClientId: '465631514254-20g8in259ejtqemk8hvmiu33fnj834op.apps.googleusercontent.com',
    iosBundleId: 'com.example.group8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARiH87L4ejrq7YSuIigNhqZ89Gzxw8dzc',
    appId: '1:465631514254:ios:b71f8307445291644a83df',
    messagingSenderId: '465631514254',
    projectId: 'group-2acd1',
    storageBucket: 'group-2acd1.appspot.com',
    iosClientId: '465631514254-20g8in259ejtqemk8hvmiu33fnj834op.apps.googleusercontent.com',
    iosBundleId: 'com.example.group8',
  );
}
