// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Gh17-wmxLDLGmihxE5s_ufc9dxJPPEg',
    appId: '1:763870543994:web:7dce38dcb9d45fd1917bc3',
    messagingSenderId: '763870543994',
    projectId: 'form-cfb77',
    authDomain: 'form-cfb77.firebaseapp.com',
    storageBucket: 'form-cfb77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEJDJm205hjaNTSBqXBE6EVVeCOywY5b4',
    appId: '1:763870543994:android:9ff200ebfff583dc917bc3',
    messagingSenderId: '763870543994',
    projectId: 'form-cfb77',
    storageBucket: 'form-cfb77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKfB831pGsPpWgFJHUBLSGF33ecsBsAkY',
    appId: '1:763870543994:ios:de57c9ada0527760917bc3',
    messagingSenderId: '763870543994',
    projectId: 'form-cfb77',
    storageBucket: 'form-cfb77.appspot.com',
    iosClientId: '763870543994-goathco0nnpapvpfep8kptl4soojjkja.apps.googleusercontent.com',
    iosBundleId: 'com.example.form',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKfB831pGsPpWgFJHUBLSGF33ecsBsAkY',
    appId: '1:763870543994:ios:de57c9ada0527760917bc3',
    messagingSenderId: '763870543994',
    projectId: 'form-cfb77',
    storageBucket: 'form-cfb77.appspot.com',
    iosClientId: '763870543994-goathco0nnpapvpfep8kptl4soojjkja.apps.googleusercontent.com',
    iosBundleId: 'com.example.form',
  );
}
